services:
  openticket:
    environment:
      TOKEN: ${TOKEN}
    build: .
    volumes:
      - openticket:/home/container
      - ../files:/home/container/config:ro
    restart: no
    container_name: open-ticket
volumes:
  openticket:
