services:
  openticket:
    command: ["sleep", "inf"]
    build: .
    volumes:
      - openticket:/home/container
      - ../files:/home/container/configs:ro
    restart: no
    container_name: open-ticket
volumes:
  openticket:
